baseURL = "https://unb-mds.github.io/2025-2-OncoMap/"
languageCode = "pt-br"
title = "OncoMap"

canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Sprints"
    url = "/sprints/"
    weight = 20
  [[menu.main]]
    name = "Issues"
    url = "/issues/"
    weight = 30
  [[menu.main]]
    name = "Guia de Configuração"
    url = "/requisitos/" # Ajuste a URL se for diferente
    weight = 40
  [[menu.main]]
    name = "Arquitetura"
    url = "/arquitetura/"
    weight = 50